# Site settings
title: Workshop Portfolio
email: mw222rs@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This is the Workshop Portfolio for Mattias Wikstr&ouml;m, Jasmin Bejtovic and Anna Iosif.
baseurl: "/1DV607-WorkshopPortfolio/" # the subpath of your site, e.g. /blog/
url: "http://mw222rs.github.io/1DV607-WorkshopPortfolio" # the base hostname & protocol for your site
twitter_username:
github_username:  mw222rs

# Build settings
markdown: kramdown
